{% set name = "datasette-secrets" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/datasette_secrets-{{ version }}.tar.gz
  sha256: 5727ecb4be6e385ad44ba7c1b30f80e8fc3036fbcc184518c6b3e0a830c53b91

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - datasette
    - cryptography

test:
  imports:
    - datasette_secrets
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Manage secrets such as API keys for use with other Datasette plugins
  home: https://github.com/datasette/datasette-secrets
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
